linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - lll
    - maligned
    - funlen
    - dupl

issues:
  exclude-use-default: false
