linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - godox
    - lll
    - maligned

issues:
  exclude-use-default: false
