name: Go

on:
  push:
    branches: [ v1.7.4_hyperscale ]
  pull_request:
    branches: [ v1.7.4_hyperscale ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
